'use client'; 

import { ArrowLeft } from 'lucide-react';
import { useRouter } from 'next/navigation';

export default function TermsPage() {
  const router = useRouter();
    
  return (
    <div className="min-h-screen bg-[#0F1115] font-sans text-slate-300 selection:bg-emerald-500/30">
      
      <nav className="w-full pt-6 px-6 max-w-3xl mx-auto">
        <button 
          onClick={() => router.back()} 
          className="inline-flex items-center gap-2 text-xs font-bold text-slate-400 hover:text-white transition-colors cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4" /> Back
        </button>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-12 pb-24">
        <h1 className="text-3xl font-extrabold text-white mb-2">Terms of Service</h1>
        <p className="mb-10 text-sm font-medium text-emerald-500">Last updated: August 2026</p>
        
        <p className="mb-8 text-sm leading-relaxed">
          Welcome to Investment IQ. By accessing, browsing, or logging into this responsive website using your Google account, you agree to comply with and be bound by the following Terms and Conditions. If you do not agree, please do not use this website.
        </p>
        
        <div className="space-y-8 text-sm leading-relaxed">
          
          <section>
            <h2 className="text-lg font-bold text-white mb-3">1. No Financial Advice – Educational Information Only</h2>
            <p>All content, calculation tools, dashboard views, and AI-generated analysis provided by Investment IQ are intended solely for educational, informational, and software demonstration purposes. Investment IQ is not an Australian Financial Services (AFS) licensee. We do not provide financial product advice, broker services, or investment recommendations. You should seek independent professional advice before making any financial decisions.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">2. AI Generation & Alpha Software Disclaimer</h2>
            <p>Investment IQ is currently operating in an "Alpha" testing phase. You acknowledge that much of the content is generated by Artificial Intelligence (AI) as a user interface demonstration. AI-generated financial data can be volatile, inaccurate, outdated, or entirely hallucinated. Investment IQ makes no guarantees regarding the accuracy, completeness, or reliability of any data presented.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">3. Account Creation and Security</h2>
            <p className="mb-2">To access platform features, you must register by linking your Google account.</p>
            <ul className="list-disc pl-5 space-y-2 text-slate-400">
              <li>You are entirely responsible for maintaining the security of your logged-in session.</li>
              <li>You must notify us immediately if you suspect any unauthorized access to your account profile.</li>
              <li>We reserve the absolute right to suspend, restrict, or terminate your user account at any time, without prior notice, if we detect malicious activity or a breach of these terms.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">4. Intellectual Property and Acceptable Use</h2>
            <p className="mb-2">All software code, user interface designs, text, and unique tools displayed on Investment IQ are our exclusive property. You are strictly prohibited from:</p>
            <ul className="list-disc pl-5 space-y-2 text-slate-400">
              <li>Reverse-engineering or attempting to disrupt our database infrastructure.</li>
              <li>Using automated scripts, bots, or scrapers to extract data from our platform.</li>
              <li>Using the website for any illegal or unauthorized activities.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">5. Reliance on Third-Party Infrastructure</h2>
            <p>Investment IQ relies on third-party cloud hosting and infrastructure providers, including Vercel and Supabase. We make no guarantees of uninterrupted website availability and bear zero liability for platform downtime, database connectivity errors, or sudden server failures.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">6. Limitation of Liability</h2>
            <p>By using this service, you expressly agree that Investment IQ bears zero liability for any direct or indirect financial losses, damages, or consequences resulting from your use of this platform. All investment actions or financial tracking you undertake are entirely at your own risk.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">7. Governing Law</h2>
            <p>These terms are governed by and construed in accordance with the laws of Australia. Any disputes arising from your use of this platform will be subject to the exclusive jurisdiction of the courts of Australia.</p>
          </section>

        </div>
      </main>
    </div>
  );
}