'use client'; // ✨ Added this because useRouter is a client-side hook
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { useRouter } from 'next/navigation';
export default function TermsPage() {
const router = useRouter();
  return (
    <div className="min-h-screen bg-[#0F1115] font-sans text-slate-300 selection:bg-emerald-500/30">
      
      <nav className="w-full pt-6 px-6 max-w-3xl mx-auto">
        <button 
          onClick={() => router.back()} 
          className="inline-flex items-center gap-2 text-xs font-bold text-slate-400 hover:text-white transition-colors cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4" /> Back
        </button>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-12 pb-24">
        <h1 className="text-3xl font-extrabold text-white mb-2">Terms of Service</h1>
        <p className="mb-10 text-sm font-medium text-emerald-500">Last updated: August 2026</p>
        
        <div className="space-y-8 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-bold text-white mb-3">1. No Financial Advice – General Information Only</h2>
            <p>All content, tools, and AI-generated analysis provided by Investment IQ are intended solely for educational, informational, and software demonstration purposes. Investment IQ is <strong>not</strong> an Australian Financial Services (AFS) licensee. We do not provide financial product advice, broker services, or investment recommendations.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">2. AI Generation & Alpha Software</h2>
            <p>Investment IQ is currently operating in an "Alpha" testing phase. You acknowledge that much of the content is generated by Artificial Intelligence (AI) as a UI demonstration. AI-generated financial data can be volatile, inaccurate, or entirely hallucinated. Investment IQ makes no guarantees regarding the accuracy of any data presented.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">3. Limitation of Liability</h2>
            <p>By using this service, you expressly agree that Investment IQ bears zero liability for any direct or indirect financial losses, damages, or consequences resulting from your use of this platform. All investment actions you take are entirely at your own risk.</p>
          </section>
        </div>
      </main>
    </div>
  );
}